language: cpp

#before_install:
#  - sudo pip install PyBOMBS
#  - pybombs auto-config
#  - pybombs recipes add-defaults
#  - pybombs install uhd
##  - mkdir ~/toolchain-uhd
##  - pybombs prefix init ~/toolchain-uhd -a uhdprefix
##  - pybombs -p uhdprefix install uhd
##  - source ~/toolchain-uhd/setup_env.sh

os:
  - linux

dist: bionic

matrix:
  include:
    - compiler: gcc
      os: linux
      dist: bionic
      env: COMPILER=g++-5
    - compiler: clang
      os: linux
      dist: bionic
      env: COMPILER=clang++-6.0
  exclude:
    - compiler: gcc
    - compiler: clang

addons:
  apt:
    packages:
      - cmake
      - clang-6.0
      - gcc-5
      - g++-5
      - python-pip
      - python3-pip
      - libuhd-dev

script:
  - echo $CXX; echo $CC
  - mkdir build && cd build
  - cmake ..
  - make

notifications:
  slack:
    secure: h5AYGVV90kulQHihxIrR1Adf78PXL7V+UIDdn8Ts/vpmV972bONud9XXkTZGVz/Dv6GqmLYXHRVaaFfex3dB5kJwn4rWtpR3nyAFF606ZRgIIucph+vd/xWCexf8vwYzmEQ5zZ3J0Ixw/LLVB+Yk/wShcIlupr4escnfmfMEPkynR90Dgs18mMWGa1iep4eeayFrGrj4FHIloGyifoYHBqpAyCJgsfw5IuUVfDXuFBOH67AUCLmn7hqp+7xDHEz4CkX8EduM6HndG5TLDOZgxHqoGQ67nU86pyB9pg7TgxfbZlVJ7Sc9W8eC//Gv0b0BspLQefe0rTCSl2FEuz7Y6160tAzL4s3EabFxDcU3IC0T9U4WVvSfLsv94EftsUnhgvTu/ggr2uzACT5FsyabRfgt0ZHZvg5ypeBwkOzKOCgVFLo1HqBRze/4GfAs1e9RsEp+lxjkwWbl5+rwvcLbs1aiM9PJ/pBJq3lQhmAq3wvyLkvyOT5r+Y17hHqvl3p+PrkGvYaHs5jLrykN1hCYqY96KOLELHMyj/ugSWQoPmUUUS8zhOY8byOBORcykGe/0ErZWAeVXrLaJ+IGKvQUw74HQSnicSGmTdVHFqZhHYAaGVsViRrSP7xncDAG1G16nw3XGNqs+5IJQw6L9gBRlSUKU7o4lp0uBq2PgpbEf9M=
